// The loop catalog. Underscore prefix keeps Vercel from serving this as a
// route, same as api/_license.js.
//
// One entry per loop:
//   preview   40/30s mp3 that ships with the site, in uploads_opt/loops/
//   download  asset name in the GitHub release (full file, not in this repo)
//   key       only where it was actually in the source filename, never guessed
//
// Cover art is not listed: it is uploads_opt/loops/covers/<id>.jpg, with the
// wordmark-cropped hero variant next to it in covers/hero/<id>.jpg.
module.exports = [
  { id: 'giftig', title: 'Giftig', bpm: 80, key: 'Bbm', preview: 'giftig.mp3', download: 'Giftig-80-Bbm-@TagoBeats.wav' },
  { id: 'snowflake', title: 'Snowflake', bpm: 83, key: 'Dm', preview: 'snowflake.mp3', download: 'Snowflake-83-Dm-@TagoBeats.wav' },
  { id: 'trip', title: 'Trip', bpm: 102, preview: 'trip.mp3', download: 'Trip-102-@TagoBeats.wav' },
  { id: 'forfeit', title: 'Forfeit', bpm: 120, key: 'Dm', preview: 'forfeit.mp3', download: 'Forfeit-120-Dm-@TagoBeats.wav' },
  { id: 'liquid', title: 'Liquid', bpm: 120, preview: 'liquid.mp3', download: 'Liquid-120-@TagoBeats.wav' },
  { id: 'fx', title: 'FX', bpm: 122, key: 'F#m', preview: 'fx.mp3', download: 'FX-122-F-sharp-m-@TagoBeats.wav' },
  { id: 'cheesy', title: 'Cheesy', bpm: 128, key: 'Cm', preview: 'cheesy.mp3', download: 'Cheesy-128-Cm-@TagoBeats.wav' },
  { id: 'different', title: 'Different', bpm: 128, key: 'A#m', preview: 'different.mp3', download: 'Different-128-A-sharp-m-@TagoBeats.wav' },
  { id: 'emergency', title: 'Emergency', bpm: 130, preview: 'emergency.mp3', download: 'Emergency-130-@TagoBeats.wav' },
  { id: 'future', title: 'Future', bpm: 130, preview: 'future.mp3', download: 'Future-130-@TagoBeats.wav' },
  { id: 'paddle', title: 'Paddle', bpm: 130, key: 'C#m', preview: 'paddle.mp3', download: 'Paddle-130-C-sharp-m-@TagoBeats.wav' },
  { id: 'suspicious', title: 'Suspicious', bpm: 130, key: 'C#m', preview: 'suspicious.mp3', download: 'Suspicious-130-C-sharp-m-@TagoBeats.wav' },
  { id: 'mansion', title: 'Mansion', bpm: 132, key: 'Dm', preview: 'mansion.mp3', download: 'Mansion-132-Dm-@TagoBeats.wav' },
  { id: 'playlist', title: 'Playlist', bpm: 133, key: 'G#m', preview: 'playlist.mp3', download: 'Playlist-133-G-sharp-m-@TagoBeats.wav' },
  { id: 'night-shift', title: 'Night Shift', bpm: 135, key: 'Ebm', preview: 'night-shift.mp3', download: 'Night-Shift-135-Ebm-@TagoBeats.wav' },
  { id: 'burg', title: 'Burg', bpm: 136, key: 'C#m', preview: 'burg.mp3', download: 'Burg-136-C-sharp-m-@TagoBeats.wav' },
  { id: 'lover', title: 'Lover', bpm: 137, key: 'Am', preview: 'lover.mp3', download: 'Lover-137-Am-@TagoBeats.wav' },
  { id: 'arcade-lab', title: 'Arcade Lab', bpm: 140, key: 'Am', preview: 'arcade-lab.mp3', download: 'Arcade-Lab-140-Am-@TagoBeats.wav' },
  { id: 'foggy-head', title: 'Foggy Head', bpm: 140, key: 'F#m', preview: 'foggy-head.mp3', download: 'Foggy-Head-140-F-sharp-m-@TagoBeats.wav' },
  { id: 'jupiter', title: 'Jupiter', bpm: 140, key: 'Em', preview: 'jupiter.mp3', download: 'Jupiter-140-Em-@TagoBeats.wav' },
  { id: 'lost', title: 'Lost', bpm: 140, key: 'Am', preview: 'lost.mp3', download: 'Lost-140-Am-@TagoBeats.wav' },
  { id: 'melt-down', title: 'Melt Down', bpm: 140, key: 'Am', preview: 'melt-down.mp3', download: 'Melt-Down-140-Am-@TagoBeats.wav' },
  { id: 'mission', title: 'Mission', bpm: 140, key: 'Gm', preview: 'mission.mp3', download: 'Mission-140-Gm-@TagoBeats.wav' },
  { id: 'shuttle', title: 'Shuttle', bpm: 140, preview: 'shuttle.mp3', download: 'Shuttle-140-@TagoBeats.wav' },
  { id: 'super-einsicht', title: 'Super Einsicht', bpm: 140, preview: 'super-einsicht.mp3', download: 'Super-Einsicht-140-@TagoBeats.wav' },
  { id: 'transit', title: 'Transit', bpm: 140, key: 'Ebm', preview: 'transit.mp3', download: 'Transit-140-Ebm-@TagoBeats.wav' },
  { id: 'vintage', title: 'Vintage', bpm: 140, preview: 'vintage.mp3', download: 'Vintage-140-@TagoBeats.wav' },
  { id: 'vaporized', title: 'Vaporized', bpm: 140, key: 'C#m', preview: 'vaporized.mp3', download: 'Vaporized-140-C-sharp-m-@TagoBeats.wav' },
  { id: 'shooting-star', title: 'Shooting Star', bpm: 150, key: 'Gm', preview: 'shooting-star.mp3', download: 'Shooting-Star-150-Gm-@TagoBeats.wav' },
  { id: 'fly-high', title: 'Fly High', bpm: 150, key: 'Am', preview: 'fly-high.mp3', download: 'Fly-High-150-Am-@TagoBeats.wav' },
  { id: 'watch-out', title: 'Watch Out', bpm: 160, preview: 'watch-out.mp3', download: 'Watch-Out-160-@TagoBeats.wav' },
  { id: 'fresh-and-fruity', title: 'Fresh And Fruity', bpm: 160, key: 'Em', preview: 'fresh-and-fruity.mp3', download: 'Fresh-And-Fruity-160-Em-@TagoBeats.wav' },
  { id: 'first-class', title: 'First Class', bpm: 143, key: 'D#m', preview: 'first-class.mp3', download: 'First-Class-143-D-sharp-m-@TagoBeats.wav' },
  { id: 'blood-moon', title: 'Blood Moon', bpm: 145, preview: 'blood-moon.mp3', download: 'Blood-Moon-145-@TagoBeats.wav' },
  { id: 'fuck-bro', title: 'Fuck Bro', bpm: 146, key: 'Fm', preview: 'fuck-bro.mp3', download: 'Fuck-Bro-146-Fm-@TagoBeats.wav' },
  { id: 'ghost', title: 'Ghost', bpm: 147, key: 'Gm', preview: 'ghost.mp3', download: 'Ghost-147-Gm-@TagoBeats.wav' },
  { id: 'blockbuster', title: 'Blockbuster', bpm: 150, preview: 'blockbuster.mp3', download: 'Blockbuster-150-@TagoBeats.wav' },
  { id: 'fairy-tail', title: 'Fairy Tail', bpm: 150, key: 'G#m', preview: 'fairy-tail.mp3', download: 'Fairy-Tail-150-G-sharp-m-@TagoBeats.wav' },
  { id: 'haunted', title: 'Haunted', bpm: 150, preview: 'haunted.mp3', download: 'Haunted-150-@TagoBeats.wav' },
  { id: 'letter', title: 'Letter', bpm: 150, preview: 'letter.mp3', download: 'Letter-150-@TagoBeats.wav' },
  { id: 'no-incarnation', title: 'No Incarnation', bpm: 150, preview: 'no-incarnation.mp3', download: 'No-Incarnation-150-@TagoBeats.wav' },
  { id: 'emotional-damage', title: 'Emotional Damage', bpm: 150, key: 'Em', preview: 'emotional-damage.mp3', download: 'Emotional-Damage-150-Em-@TagoBeats.wav' },
  { id: 'pm', title: 'PM', bpm: 150, key: 'F#m', preview: 'pm.mp3', download: 'PM-150-F-sharp-m-@TagoBeats.wav' },
  { id: 'space-station', title: 'Space Station', bpm: 150, preview: 'space-station.mp3', download: 'Space-Station-150-@TagoBeats.wav' },
  { id: 'superior', title: 'Superior', bpm: 150, key: 'Ebm', preview: 'superior.mp3', download: 'Superior-150-Ebm-@TagoBeats.wav' },
  { id: 'boomboom', title: 'Boomboom', bpm: 152, key: 'C#m', preview: 'boomboom.mp3', download: 'Boomboom-152-C-sharp-m-@TagoBeats.wav' },
  { id: 'late-night', title: 'Late Night', bpm: 153, key: 'F#m', preview: 'late-night.mp3', download: 'Late-Night-153-F-sharp-m-@TagoBeats.wav' },
  { id: 'studio-time', title: 'Studio Time', bpm: 155, key: 'Fm', preview: 'studio-time.mp3', download: 'Studio-Time-155-Fm-@TagoBeats.wav' },
  { id: 'goodbye', title: 'Goodbye', bpm: 158, key: 'Bm', preview: 'goodbye.mp3', download: 'Goodbye-158-Bm-@TagoBeats.wav' },
  { id: 'balance', title: 'Balance', bpm: 160, key: 'F#m', preview: 'balance.mp3', download: 'Balance-160-F-sharp-m-@TagoBeats.wav' },
  { id: 'dead-ass', title: 'Dead Ass', bpm: 160, key: 'Em', preview: 'dead-ass.mp3', download: 'Dead-Ass-160-Em-@TagoBeats.wav' },
  { id: 'fragile', title: 'Fragile', bpm: 160, preview: 'fragile.mp3', download: 'Fragile-160-@TagoBeats.wav' },
  { id: 'free', title: 'Free', bpm: 160, key: 'Gm', preview: 'free.mp3', download: 'Free-160-Gm-@TagoBeats.wav' },
  { id: 'heal', title: 'Heal', bpm: 160, preview: 'heal.mp3', download: 'Heal-160-@TagoBeats.wav' },
  { id: 'mystery', title: 'Mystery', bpm: 160, preview: 'mystery.mp3', download: 'Mystery-160-@TagoBeats.wav' },
  { id: 'ocb', title: 'OCB', bpm: 160, key: 'Em', preview: 'ocb.mp3', download: 'OCB-160-Em-@TagoBeats.wav' },
  { id: 'piano-pesto', title: 'Piano Pesto', bpm: 160, key: 'Gm', preview: 'piano-pesto.mp3', download: 'Piano-Pesto-160-Gm-@TagoBeats.wav' },
  { id: 'spider', title: 'Spider', bpm: 160, preview: 'spider.mp3', download: 'Spider-160-@TagoBeats.wav' },
  { id: 'ufo', title: 'UFO', bpm: 160, key: 'Gm', preview: 'ufo.mp3', download: 'UFO-160-Gm-@TagoBeats.wav' },
  { id: 'voice', title: 'Voice', bpm: 160, preview: 'voice.mp3', download: 'Voice-160-@TagoBeats.wav' },
  { id: 'cheese', title: 'Cheese', bpm: 166, key: 'Fm', preview: 'cheese.mp3', download: 'Cheese-166-Fm-@TagoBeats.wav' },
  { id: 'red', title: 'Red', bpm: 170, preview: 'red.mp3', download: 'Red-170-@TagoBeats.wav' },
  { id: 'shredder', title: 'Shredder', bpm: 170, preview: 'shredder.mp3', download: 'Shredder-170-@TagoBeats.wav' },
  { id: 'death-wish', title: 'Death Wish', bpm: 180, preview: 'death-wish.mp3', download: 'Death-Wish-180-@TagoBeats.wav' },
  { id: 'past', title: 'Past', bpm: 180, key: 'F#m', preview: 'past.mp3', download: 'Past-180-F-sharp-m-@TagoBeats.wav' },
]
